spring:
  application:
    name: mock-company-webapp

  # In memory database that is populated dynamically from DataPopulator
  datasource:
    url: jdbc:postgresql://localhost:5432/products
    username: db_maintainer
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
